//! Access to the bun bytes embedded at build time.
//!
//! Production reads constants emitted by `build.rs` into
//! `$OUT_DIR/bun_meta.rs`. When `AIONUI_EMBED_BUN` is unset at build time,
//! `build.rs` emits a stub with `HAS_EMBEDDED_BUN = false`, which makes
//! `resolve_bun()` fall back to `which()` — exactly the pre-embed behavior.

/// Raw compile-time constants generated by `build.rs` into `$OUT_DIR/bun_meta.rs`.
pub(crate) mod consts {
    include!(concat!(env!("OUT_DIR"), "/bun_meta.rs"));
}

/// Indirection trait so tests can inject a fake embedded payload instead
/// of linking the real (potentially 30MB+) compressed blob.
pub trait EmbeddedBun: Send + Sync {
    fn has(&self) -> bool;
    fn blob(&self) -> &'static [u8];
    fn sha256(&self) -> &'static str;
    fn version(&self) -> &'static str;
}

/// Production implementation backed by constants from `bun_meta.rs`.
#[derive(Debug, Default, Clone, Copy)]
pub struct ProductionEmbed;

impl EmbeddedBun for ProductionEmbed {
    fn has(&self) -> bool {
        consts::HAS_EMBEDDED_BUN
    }
    fn blob(&self) -> &'static [u8] {
        consts::BUN_BLOB
    }
    fn sha256(&self) -> &'static str {
        consts::BUN_SHA256
    }
    fn version(&self) -> &'static str {
        consts::BUN_VERSION
    }
}

#[cfg(test)]
pub(crate) struct FakeEmbed {
    pub has: bool,
    pub blob: &'static [u8],
    pub sha256: &'static str,
    pub version: &'static str,
}

#[cfg(test)]
impl EmbeddedBun for FakeEmbed {
    fn has(&self) -> bool {
        self.has
    }
    fn blob(&self) -> &'static [u8] {
        self.blob
    }
    fn sha256(&self) -> &'static str {
        self.sha256
    }
    fn version(&self) -> &'static str {
        self.version
    }
}

/// Raw compile-time constants generated by `build.rs` into
/// `$OUT_DIR/node_meta.rs`.
pub(crate) mod node_consts {
    include!(concat!(env!("OUT_DIR"), "/node_meta.rs"));
}

/// Indirection trait for the bundled node blob (parallels `EmbeddedBun`).
pub trait EmbeddedNode: Send + Sync {
    fn has(&self) -> bool;
    fn blob(&self) -> &'static [u8];
    fn sha256(&self) -> &'static str;
    fn version(&self) -> &'static str;
    /// Stable directory name `node-<version>-<sha12>` derived at build time.
    fn dir_name(&self) -> &'static str;
}

#[derive(Debug, Default, Clone, Copy)]
pub struct ProductionEmbedNode;

impl EmbeddedNode for ProductionEmbedNode {
    fn has(&self) -> bool {
        node_consts::HAS_EMBEDDED_NODE
    }
    fn blob(&self) -> &'static [u8] {
        node_consts::NODE_BLOB
    }
    fn sha256(&self) -> &'static str {
        node_consts::NODE_SHA256
    }
    fn version(&self) -> &'static str {
        node_consts::NODE_VERSION
    }
    fn dir_name(&self) -> &'static str {
        node_consts::NODE_DIR_NAME
    }
}

#[cfg(test)]
pub(crate) struct FakeEmbedNode {
    pub has: bool,
    pub blob: &'static [u8],
    pub sha256: &'static str,
    pub version: &'static str,
    pub dir_name: &'static str,
}

#[cfg(test)]
impl EmbeddedNode for FakeEmbedNode {
    fn has(&self) -> bool {
        self.has
    }
    fn blob(&self) -> &'static [u8] {
        self.blob
    }
    fn sha256(&self) -> &'static str {
        self.sha256
    }
    fn version(&self) -> &'static str {
        self.version
    }
    fn dir_name(&self) -> &'static str {
        self.dir_name
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn production_embed_respects_env_gate() {
        // Unless AIONUI_EMBED_BUN=1 at build time, ProductionEmbed reports "no embed".
        assert!(!ProductionEmbed.has());
        assert_eq!(ProductionEmbed.blob(), b"");
    }

    #[test]
    fn fake_embed_returns_injected_values() {
        let fake = FakeEmbed {
            has: true,
            blob: b"hello",
            sha256: "deadbeef",
            version: "9.9.9",
        };
        assert!(fake.has());
        assert_eq!(fake.blob(), b"hello");
        assert_eq!(fake.sha256(), "deadbeef");
        assert_eq!(fake.version(), "9.9.9");
    }

    #[test]
    fn production_embed_node_respects_env_gate() {
        assert!(!ProductionEmbedNode.has());
        assert_eq!(ProductionEmbedNode.blob(), b"");
    }

    #[test]
    fn fake_embed_node_returns_injected_values() {
        let fake = FakeEmbedNode {
            has: true,
            blob: b"hello",
            sha256: "deadbeef",
            version: "22.11.0",
            dir_name: "node-22.11.0-deadbeef0000",
        };
        assert!(fake.has());
        assert_eq!(fake.blob(), b"hello");
        assert_eq!(fake.sha256(), "deadbeef");
        assert_eq!(fake.version(), "22.11.0");
        assert_eq!(fake.dir_name(), "node-22.11.0-deadbeef0000");
    }
}
