//! Build-time metadata for the optional bun runtime.
//!
//! Bun is no longer embedded in AionCore. The runtime still supports an
//! explicit `AIONUI_BUN_PATH` override or a system-installed `bun`, but
//! packaged builds should not download or bundle bun/bunx implicitly.

use std::fs;
use std::path::Path;

fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR");
    let meta_path = Path::new(&out_dir).join("bun_meta.rs");
    write_meta_stub(&meta_path);
}

fn write_meta_stub(meta_path: &Path) {
    let out_dir = meta_path.parent().expect("OUT_DIR parent");
    let stub_blob = out_dir.join("bun.blob.zst");
    if !stub_blob.is_file() {
        fs::write(&stub_blob, []).expect("write stub blob");
    }
    let body = "// @generated by build.rs — do not edit\n\
                pub const BUN_BLOB: &[u8] = include_bytes!(\"bun.blob.zst\");\n\
                pub const BUN_SHA256: &str = \"\";\n\
                pub const BUN_VERSION: &str = \"\";\n\
                pub const HAS_EMBEDDED_BUN: bool = false;\n";
    fs::write(meta_path, body).expect("write stub bun_meta.rs");
}
